### Creating Arrays

In [1]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4,5])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=float)
c =  np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]], dtype=float)
print(c)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


### Initial Placeholders

In [25]:
np.zeros((3,4)) 

b = np.ones((2, 2, 3) , dtype=np.int16)
print(b)

d = np.arange(10,25,5)
print(d)

c = np.linspace(0,2,9)
print(c)


e = np.full((2,2),7)
print(e)

f = np.eye(2)
print(f)

g = np.random.random((2,2))
print(g)

h = np.empty((3,2))
print(h)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.02604672 0.82500695]
 [0.97573405 0.12916356]]
[[5.e-324 5.e-324]
 [5.e-324 5.e-324]
 [5.e-324 5.e-324]]
