In [1]:
import numpy as np

In [7]:
import numpy as np
'''You received three different sensor readings as Python lists
(they have different lengths):Python
sensor_a = [22.1, 23.4, 21.9, 24.0]
sensor_b = [1013.2, 1015.7, 1012.1]
sensor_c = [45, 48, 46, 44, 50, 47]
Turn them into a single 2D NumPy array (6 rows × 3 columns) by padding
missing values with np.nan.
Final shape must be (6,3). Print the array.'''

sensor_a = [22.1, 23.4, 21.9, 24.0]
sensor_b = [1013.2, 1015.7, 1012.1]
sensor_c = [45, 48, 46, 44, 50, 47]

max_len = 6

a = np.pad(np.array(sensor_a, dtype=float), (0, max_len - len(sensor_a)), constant_values=np.nan)
b = np.pad(np.array(sensor_b, dtype=float), (0, max_len - len(sensor_b)), constant_values=np.nan)
c = np.pad(np.array(sensor_c, dtype=float), (0, max_len - len(sensor_c)), constant_values=np.nan)

result = np.column_stack((a,b,c))

print("Final array:\n",result)
print("Shape:",result.shape)



Final array:
 [[  22.1 1013.2   45. ]
 [  23.4 1015.7   48. ]
 [  21.9 1012.1   46. ]
 [  24.     nan   44. ]
 [   nan    nan   50. ]
 [   nan    nan   47. ]]
Shape: (6, 3)


### Question 2

In [24]:
'''Create a checkerboard 8×8 array containing only 0 and 1 alternating (like a chessboard),
without using any loops.
Tip: use np.zeros, np.ones, slicing and/or reshape + transpose tricks.'''

board = np.zeros((8,8), dtype=int)

board[::2, 1::2] = 1
board[1::2, ::2] = 1

print(board)

# or

arr = np.arange(64) % 2
board = arr.reshape(8,8)

print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


### Question 5

In [9]:
'''Create a 1D array of 120 evenly spaced numbers between 0 and 599 (inclusive).
 Reshape it to (5, 4, 6) → call this A Then reshape A to (4, 5, 6) → call this B Then transpose B
   to swap axis 0 and axis 1 → call this 
CNow flatten A, B, and C using both .flatten() and .ravel(). Are all six 1D versions identical? Why / why not?'''

arr = np.linspace(0, 599, 120)

A = arr.reshape((5,4,6))
B = A.reshape((4,5,6))
C = B.transpose(1,0,2)

f1 = A.flatten()
f2 = B.flatten()
f3 = C.flatten()

r1 = A.ravel()
r2 = B.ravel()
r3 = C.ravel()

print(np.array_equal(f1,f2))
print(np.array_equal(f1,f3))
print(np.array_equal(r1,r2))
print(np.array_equal(r1,r3))


True
False
True
False


### Question 4

In [ ]:
'''Explain (in your own words, 3–5 sentences) the practical difference between .ravel() and .flatten() when you are:
preparing features for a classical ML model
feeding data into a convolutional neural network input layer'''

'''Both ravel and flatten methods converts the multidimensional array to 1D array , ravel creats the view(reference)
of the original array,making the memore more efficient, whilw thw flatten method generate the copy of the original
array, modifications done using flatten method does not affect the original array while ravel affetcts original one'''

'''Both **`.ravel()`** and **`.flatten()`** convert a multidimensional NumPy array into a **1D array**.
The `.ravel()` method usually returns a **view (reference)** of the original array, so it is 
**more memory-efficient**, and changes to it may affect the original data. In contrast, `.flatten()`
 always returns a **copy**, so modifying it does **not change the original array**.
When preparing features for **classical machine learning models**, `.ravel()` is often preferred because 
it avoids unnecessary memory duplication. However, when feeding data into systems like a **convolutional 
neural network input layer**, `.flatten()` can be safer if you want to prevent accidental modification
 of the original dataset.
'''

### Question 5

In [9]:
'''Create a 3×4×5 array filled with sequential numbers 0 to 59 (in C-order).
Transpose it so that the fastest changing dimension becomes the first one.
What is the new shape? How many numbers are now in each “slice” along the new axis 0?'''

array = np.arange(60).reshape((3, 4,5))
print("Array:\n",array)
print("Shape:\n",array.shape)

transposed = array.transpose(2, 0, 1)
print("Transposed:\n",transposed)
print("new_shape",transposed.shape)



Array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
Shape:
 (3, 4, 5)
Transposed:
 [[[ 0  5 10 15]
  [20 25 30 35]
  [40 45 50 55]]

 [[ 1  6 11 16]
  [21 26 31 36]
  [41 46 51 56]]

 [[ 2  7 12 17]
  [22 27 32 37]
  [42 47 52 57]]

 [[ 3  8 13 18]
  [23 28 33 38]
  [43 48 53 58]]

 [[ 4  9 14 19]
  [24 29 34 39]
  [44 49 54 59]]]
new_shape (5, 3, 4)


### Question 6

In [11]:
'''You have sales data shaped (quarters, regions, products) = (4, 5, 8).
You want to calculate total sales per product across all quarters and regions quickly.
Which single axis should you sum over after which transpose?
Write the shortest chain of .transpose(...) + .sum(...) that gives you a 1D array of length 8.'''

sales = np.arange(4*5*8).reshape(4,5,8)
print("Original shape:", sales.shape)

transpose = sales.transpose(2,0,1)
print("After Transpose;",transpose.shape)

total_sales_per_product = transposed.sum(axis=(1,2))

print("Total sales per product:")
print(total_sales_per_product)

print("Result shape:", total_sales_per_product.shape)

Original shape: (4, 5, 8)
After Transpose; (8, 4, 5)
Total sales per product:
[330 342 354 366 378]
Result shape: (5,)
