In [1]:
import numpy as np

### QUESTION---1

In [11]:
'''Simple Conversion: Convert the list [10, 20, 30, 40] to a NumPy array. Print it, then access the second
element (index 1).What dtype does it default to? (Hint: Check with arr.dtype.)'''

list = [10, 20, 30, 40]

arr = np.array([list])

print("Array: ",arr)

print("Second element: ",arr[::2])

Array:  [[10 20 30 40]]
Second element:  [[10 20 30 40]]


### QUESTION---2

In [16]:
'''Nested List to 2D Array: Turn [[1, 2, 3], [4, 5, 6]] into a NumPy array. Print its shape (arr.shape). 
What happens if you add a mismatched inner list like [7, 8]?'''

list1 = [[1, 2, 3], [4, 5, 6]]

arr = np.array(list1)
print(arr)
print("Dimension:",arr.ndim)
print("Shape:",arr.shape)

print("\n After adding mismatched list")
lst2 = [[1, 2, 3], [4, 5, 6], [7, 8]]
try :
    arr2 = np.array(lst2)
    print(arr2)
    print("Shape:", arr2.shape)
except ValueError as e:
        print("Error:", e)


[[1 2 3]
 [4 5 6]]
Dimension: 2
Shape: (2, 3)

 After adding mismatched list
Error: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.


### QUESTION---3

In [23]:
'''Element-Wise Ops: Create a list lst = [1, 2, 3, 4] and array arr = np.array([1, 2, 3, 4]). 
Add 10 to every element in both (loop for list, direct for array).
Time both ops with 10,000 repeats. Which is faster? Why? 
(Bonus: Try multiplying by 2.)'''

import numpy as np
import time 

list = [1, 2, 3, 4]
arr = np.array([1, 2, 3, 4])

#  -----list operation----

start = time.time()
for a in range(10000):
    result_list = []
    for i in list:
        result_list.append(i + 10)

end = time.time()
list_time = end - start


# -----Numpy operation-----
start = time.time()
for a in range(10000):
    result_arr = arr + 10

end = time.time()
arr_time = end - start


print("List result:",result_list)
print("List array:",result_arr)

print("List time: ", list_time)
print("Array time: ", arr_time)

# ----- Bonus Multiplication-----
start = time.time()
for a in range(10000):
    result_list_mul= []
    for i in list:
        result_list_mul.append(i * 2)
end = time.time()
print("List multiply time: ",end - start)

start = time.time()
for a in range(10000):
    result_arr_mul = arr * 2

end = time.time()
print("Array multiply time: ",end - start)



List result: [11, 12, 13, 14]
List array: [11 12 13 14]
List time:  0.006730556488037109
Array time:  0.01744389533996582
List multiply time:  0.00564122200012207
Array multiply time:  0.010584115982055664


### ----- Question 4-----

In [2]:
'''Slicing Surprise: Slice the first two elements from lst and arr above. Modify the slice (e.g., set to 99). Does it 
affect the original? Explain the mutability difference.'''

import numpy as np

lst = [1, 2, 3, 4]
arr = np.array([1, 2, 3, 4])

# create slices 
list_slice = lst[:2]
arr_slice = arr[:2]

print("List slice:",list_slice)
print("Array slice:",arr_slice)

print("\n Modified slice:")
list_slice[0] = 99
arr_slice[0] = 99
print("List slice:",list_slice)
print("Array slice:",arr_slice)

print("\nOriginal structures:")
print("Original list:",lst)
print("Original array:",arr)




List slice: [1, 2]
Array slice: [1 2]

 Modified slice:
List slice: [99, 2]
Array slice: [99  2]

Original structures:
Original list: [1, 2, 3, 4]
Original array: [99  2  3  4]


### Question 5

In [13]:
'''Uniform Arrays: Create a 3x3 array of zeros (float dtype). Then, one of ones (int dtype). 
Stack them vertically with np.vstack and print the result. What's the new shape?'''

# zeros array
Zeros_array = np.zeros((3,3), dtype=float)

# ones array
Ones_array = np.ones((3,3), dtype=int)

# Verticle stack
result = np.vstack((Zeros_array,Ones_array))

print("Zeros array:\n",Zeros_array)
print("Oness array:\n",Ones_array)
print("Verticle array:\n",result)

print("Shape of reultant array:",result.shape)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Oness array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Verticle array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape of reultant array: (6, 3)


### Question 6


In [16]:
'''Sequence Generators: Use np.arange(0, 20, 2) to make an even-number array up to 18.
 Then np.linspace(0, 10, 6) for 6 evenly spaced points.
 Concat them horizontally (np.hstack)—what's the output?'''

even_array = np.arange(0, 20, 2)

linspace = np.linspace(0, 10, 6)

# Concating the both
result = np.hstack((even_array,linspace))


print("Even number array up to 18:\n",even_array)
print("Linspacee for 6 evenly spaced points:\n",linspace)
print("Concated array", result)

Even number array up to 18:
 [ 0  2  4  6  8 10 12 14 16 18]
Linspacee for 6 evenly spaced points:
 [ 0.  2.  4.  6.  8. 10.]
Concated array [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.  0.  2.  4.  6.  8. 10.]


### Question 7

In [21]:
'''From 1D to 3D: Start with a 1D vector [1, 2, 3]. Reshape it to a 1x3 matrix, then "promote" to a 1x1x3 tensor.
Print ndim and shape at each step. (Hint: Use np.newaxis for the tensor.)'''

vector_1d = np.array([1, 2, 3])
print("Original 1D vector:\n",vector_1d)
print("\nOriginal vector shape:\n",vector_1d.shape)

matrix_1x3 = vector_1d.reshape(1,3)
print("\n1x3 matrix:\n",matrix_1x3)
print("\n1x3 matrix shape :\n",matrix_1x3.shape)

Original 1D vector:
 [1 2 3]

Original vector shape:
 (3,)

1x3 matrix:
 [[1 2 3]]

1x3 matrix shape :
 (1, 3)


### Question 8


In [26]:
'''Real-World Matrix: Simulate a 4x3 sales matrix (rows: quarters, cols: products) with random ints 1-100 
(np.random.randint(1, 101, (4,3))). 
What's its ndim? Sum rows with arr.sum(axis=1)—interpret as quarterly totals.'''

sales_matrix = np.random.randint(1, 101, (4,3))
print("Dimension: ",sales_matrix.ndim)

print("Sales matrix:\n",sales_matrix)
q_totals = sales_matrix.sum(axis= 1)
print("\nq_total:\n",q_totals)


Dimension:  2
Sales matrix:
 [[36 53 75]
 [55 95 39]
 [44 57 88]
 [94 14 42]]

q_total:
 [164 189 189 150]


In [ ]:
'''Property Probe: Create a 2x4 array of random floats. Print its shape, ndim, size, and dtype. 
Flatten it (flatten()) vs. ravel (ravel())—are they the same? Modify one; does it affect the original?
(Key diff: copy vs. view.)'''

arr = np.random.rand(2,4)
print("Array: \n",arr)

# Properties
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Dimension: ", arr.ndim)
print("Data type: ", arr.dtype)

# Flattenin the array  (CReates copy)
flat = arr.flatten()

# ravel (creates view)
raveled = arr.ravel()

print("\nFlattend:\n",flat)
print("Raveled:\n",raveled)

# flatten modification
flat[0] = 888

# raveled modification
raveled[1] = 999

print("\---nAfter modification---")
print("Flatten:\n",flat)
print("Raveled:\n",raveled)


print("\n---Original array---")
print(arr)

Array: 
 [[0.31386081 0.51740519 0.91791493 0.86988357]
 [0.32628164 0.92590676 0.9844296  0.41645097]]
Shape:  (2, 4)
Size:  8
Dimension:  2
Data type:  float64

Flattend:
 [0.31386081 0.51740519 0.91791493 0.86988357 0.32628164 0.92590676
 0.9844296  0.41645097]
Raveled:
 [0.31386081 0.51740519 0.91791493 0.86988357 0.32628164 0.92590676
 0.9844296  0.41645097]
\---nAfter modification---
Flatten:
 [8.88000000e+02 5.17405186e-01 9.17914928e-01 8.69883572e-01
 3.26281643e-01 9.25906758e-01 9.84429600e-01 4.16450969e-01]
Raveled:
 [3.13860807e-01 9.99000000e+02 9.17914928e-01 8.69883572e-01
 3.26281643e-01 9.25906758e-01 9.84429600e-01 4.16450969e-01]

---Original array---
[[3.13860807e-01 9.99000000e+02 9.17914928e-01 8.69883572e-01]
 [3.26281643e-01 9.25906758e-01 9.84429600e-01 4.16450969e-01]]


<>:29: SyntaxWarning: "\-" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\-"? A raw string is also an option.
<>:29: SyntaxWarning: "\-" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\-"? A raw string is also an option.
C:\Users\chand\AppData\Local\Temp\ipykernel_21988\2670370323.py:29: SyntaxWarning: "\-" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\-"? A raw string is also an option.
  print("\---nAfter modification---")


### Question 10

In [12]:
'''Reshape Remix: Take a 1D array of 12 zeros. Reshape to (3,4), then (4,3). Print both. 
What error do you get trying (2,7)?Now transpose the (3,4) one—what's the new shape?
(Bonus: Chain reshape and T.)'''


Array_1D  = np.zeros(12)
print("1D Array:\n",Array_1D)

# Reshaping
reshaped1 = Array_1D.reshape(3,4)
reshaped2 = Array_1D.reshape(4,3)

# Trying (2,7)
# reshaped3 = Array_1D.reshape(2,7)  # Value error

print("\n---Reshaped Arrays---")
print("Reshaped 1:\n",reshaped1)
print("Reshaped 2:\n",reshaped2)

# printing (2,7)
# print("Reshaped 3:\n",reshaped3)

transpose = reshaped1.T
print("Transposed  array(3,4):\n",transpose)
print("Shape of the transposed array: ",transpose.shape)

# Bonus
bonus = Array_1D.reshape(3,4).T
print("\n---Bonus reshape + transpose---")
print(bonus)
print("Shape:", bonus.shape)

1D Array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

---Reshaped Arrays---
Reshaped 1:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Reshaped 2:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Transposed  array(3,4):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape of the transposed array:  (4, 3)

---Bonus reshape + transpose---
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (4, 3)
