## Numpy array and basics 
learnin about numpy

In [1]:
import numpy as np

### creating array from list


In [5]:
arr_1d = np.array([1,2,3,4,5])
print("1d Array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d Array: ",arr_2d)

1d Array:  [1 2 3 4 5]
2d Array:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [ ]:
py_list = [1,2,3,4]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication 
print("Python array multiplication: ", np_array *2) 

Python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication:  [2 4 6]


In [8]:
import time

start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.05089998245239258

 Numpy operation time:  0.007437467575073242


### creating array fom scratch

In [11]:
import numpy as np

In [2]:
zeros = np.zeros((3, 4))
print("Zero array: \n",zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

full = np.full((2, 2), 7)
print("Full array: \n",full)

random = np.random.random((2,3))
print("Random array: \n",random)

sequence = np.arange(0, 11, 3)
print("sequence array: \n",sequence)


Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.98852064 0.20271808 0.17029084]
 [0.87152269 0.26673352 0.16900131]]
sequence array: 
 [0 3 6 9]


### Vector, Matrix and Tensor

In [3]:
vector = np.array([1, 2, 3])
print("Vector: ",vector)

matrix = np.array([[1, 2, 3],
                   [2, 4, 5]])
print("Matrix: ",matrix)

tensor = np.array([[[1, 2], [2, 3]],
                   [[3, 4], [4, 5]]])
print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [2 4 5]]
Tensor:  [[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


### Array Properties

In [11]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("Size: ",arr.size)
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Data type: ",arr.dtype)

Size:  12
Shape:  (2, 2, 3)
Dimension:  3
Data type:  int64


In [21]:
arr = np.arange(12)
print("Original:",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array:\n",reshaped)

flattend = reshaped.flatten()
print("\n Flattened array: ",flattend)

# Ravel returns view instead of copy
raveled = reshaped.ravel()
print("\n Raveled: ",raveled)

# Transpose 
transpose = reshaped.T
print("\n Transpose:\n", transpose)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
