## Numpy array Operations 

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Basic Slice:",arr[2:7])
print("With step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic Slice: [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 7


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Specific element",arr_2d[1, 2])
print("Entire row:",arr_2d[0])
print("Entire coulum",arr_2d[:,2])

Specific element 6
Entire row: [1 2 3]
Entire coulum [3 6 9]


## Sorting

In [15]:
unsorted = np.array([2, 1, 3, 5, 6, 4, 8, 9, 7])
print("Sorted Array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[1, 6],
                           [5, 3],
                           [2, 4]])
print("Sorted 2D array:\n",np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array:\n",np.sort(arr_2d_unsorted, axis=1))

Sorted Array: [1 2 3 4 5 6 7 8 9]
Sorted 2D array:
 [[1 3]
 [2 4]
 [5 6]]
Sorted 2D array:
 [[1 6]
 [3 5]
 [2 4]]


### Filter


In [26]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ",even_numbers)

Even numbers:  [ 2  4  6  8 10]


### Filtering By mask


In [ ]:
mask = numbers > 5
print("Numbers Greater than 5: ",numbers[mask])


Numbers Greater than 5:  [11]


### Fancy indexing vs np.where

In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)  # Actually where stores the index of the numbers
print("NP where:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [30]:

condition_array = np.where(numbers > 5,numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Compatibility

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibilty shapes", a.shape == b.shape)

Compatibilty shapes False


In [38]:
original = ([[1, 2], [3, 4]])

new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("With row:\n",with_new_row)


new_column = np.array([[5],[9]])

with_new_col = np.hstack((original, new_column))
print("With column:\n",with_new_col)

With row:
 [[1 2]
 [3 4]
 [5 6]]
With column:
 [[1 2 5]
 [3 4 9]]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
deletion = np.delete(arr, 3)
print(deletion)

arr2 = np.array([[1, 2],
              [4,5],
              [5,6]])
deletion1 = np.delete(arr2, 1, axis=1)
print(deletion1)

[1 2 3 5 6 7 8]
[[1]
 [4]
 [5]]
