In [2]:
import numpy as np

In [7]:
import numpy as np
'''You received three different sensor readings as Python lists
(they have different lengths):Python
sensor_a = [22.1, 23.4, 21.9, 24.0]
sensor_b = [1013.2, 1015.7, 1012.1]
sensor_c = [45, 48, 46, 44, 50, 47]
Turn them into a single 2D NumPy array (6 rows × 3 columns) by padding
missing values with np.nan.
Final shape must be (6,3). Print the array.'''

sensor_a = [22.1, 23.4, 21.9, 24.0]
sensor_b = [1013.2, 1015.7, 1012.1]
sensor_c = [45, 48, 46, 44, 50, 47]

max_len = 6

a = np.pad(np.array(sensor_a, dtype=float), (0, max_len - len(sensor_a)), constant_values=np.nan)
b = np.pad(np.array(sensor_b, dtype=float), (0, max_len - len(sensor_b)), constant_values=np.nan)
c = np.pad(np.array(sensor_c, dtype=float), (0, max_len - len(sensor_c)), constant_values=np.nan)

result = np.column_stack((a,b,c))

print("Final array:\n",result)
print("Shape:",result.shape)



Final array:
 [[  22.1 1013.2   45. ]
 [  23.4 1015.7   48. ]
 [  21.9 1012.1   46. ]
 [  24.     nan   44. ]
 [   nan    nan   50. ]
 [   nan    nan   47. ]]
Shape: (6, 3)


### Question 2

In [24]:
'''Create a checkerboard 8×8 array containing only 0 and 1 alternating (like a chessboard),
without using any loops.
Tip: use np.zeros, np.ones, slicing and/or reshape + transpose tricks.'''

board = np.zeros((8,8), dtype=int)

board[::2, 1::2] = 1
board[1::2, ::2] = 1

print(board)

# or

arr = np.arange(64) % 2
board = arr.reshape(8,8)

print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


### Question 5

In [9]:
'''Create a 1D array of 120 evenly spaced numbers between 0 and 599 (inclusive).
 Reshape it to (5, 4, 6) → call this A Then reshape A to (4, 5, 6) → call this B Then transpose B
   to swap axis 0 and axis 1 → call this 
CNow flatten A, B, and C using both .flatten() and .ravel(). Are all six 1D versions identical? Why / why not?'''

arr = np.linspace(0, 599, 120)

A = arr.reshape((5,4,6))
B = A.reshape((4,5,6))
C = B.transpose(1,0,2)

f1 = A.flatten()
f2 = B.flatten()
f3 = C.flatten()

r1 = A.ravel()
r2 = B.ravel()
r3 = C.ravel()

print(np.array_equal(f1,f2))
print(np.array_equal(f1,f3))
print(np.array_equal(r1,r2))
print(np.array_equal(r1,r3))


True
False
True
False
