# Machinelearning.com

1. Import NumPy and Check the Version

In [3]:
import numpy as np


print("Numpy Version: ",np.__version__)

Numpy Version:  2.4.2


2. Create a 1D Array

In [ ]:
arr_1d = np.arange(10)
print("1D array: ",arr_1d)

1D array:  [0 1 2 3 4 5 6 7 8 9]


3. Create a Boolean Array
Create a 3×3 numpy array of all True values

In [15]:
arr = np.full((3,3), True, dtype=bool)
print(arr)

# or

arr = np.ones((3,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract Items That Satisfy a Condition
Extract all odd numbers from arr

In [19]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_arr = arr[arr % 2 == 1]
print(odd_arr)

[1 3 5 7 9]


5. Replace Items That Satisfy a Condition
Replace all odd numbers in arr with -1.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. Replace Items Without Affecting the Original Array
Replace all odd numbers in arr with -1 without modifying the original arr.

In [23]:
arr = np.arange(10)

out = np.where(arr % 2==1, -1,arr)
print("Out: ",out)
print("arr: ",arr)

Out:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr:  [0 1 2 3 4 5 6 7 8 9]


7. Reshape an Array
Convert the 1D array arr to a 2D array with 2 rows.

In [ ]:
arr = np.arange(10)


result = arr.reshape(2,-1)  # Setting to -1 automatically decides the number of cols
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]]


8. Stack Two Arrays Vertically

In [59]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.vstack([a,b])
print(result)

result = np.concatenate([a,b], axis=0)
print(result)

print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9. Stack Two Arrays Horizontally

In [61]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.hstack([a,b])
print(result)

result = np.concatenate([a,b], axis=1)
print(result)

print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


10. Generate Custom Sequences Without Hardcoding
Using only numpy functions and the input array a, produce an array that first repeats each element 3 times, then tiles the whole array 3 times.

In [1]:
import numpy as np
a = np.array([1,2,3])

result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


11. Get Common Items Between Two Arrays
Find the common items between arrays a and b.



In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print("Common Items: ",np.intersect1d(a,b))

Common Items:  [2 4]


12. Remove Items Present in Another Array
From array a, remove all items that are present in array b.

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a,b)
print(result)

[1 2 3 4]


13. Find Positions Where Two Arrays Match

In [4]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.where(a==b)
print(result)

(array([1, 3, 5, 7]),)


14. Extract Numbers Within a Given Range
From array a, extract all items between 5 and 10 (inclusive).

In [16]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

new_a = a[(a>=5) & (a<=10)]
print(new_a)

index = np.where((a>=5) & (a<=10))
print(a[index])

index = np.where(np.logical_and(a>=5, a<=10))
print(a[index])

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


15. Vectorize a Scalar Function to Work on Arrays
Convert the scalar function maxx into a vectorized version that works element-wise on arrays a and b.

In [18]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6. 7. 9. 8. 9. 7. 5.]


16. Swap Two Columns in a 2D Array


In [27]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
result = arr[:, [1, 2, 0]]
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 0]
 [4 5 3]
 [7 8 6]]


17. Swap Two Rows in a 2D Array

In [29]:
arr = np.arange(9).reshape(3,3)
print(arr)

arr[[0,2], :] = arr[[2,0], :]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


18. Reverse the Rows of a 2D Array

In [30]:
arr = np.arange(9).reshape(3,3)

result = arr[::-1]
print(result)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


19. Reverse the Columns of a 2D Array

In [35]:
arr = np.arange(9).reshape(3,3)
print(arr)
result = arr[:,::-1]
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. Create a 2D Array of Random Floats Between 5 and 10
Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.

In [40]:
arr = np.random.uniform(5, 10, (5, 3))
print(arr)

rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)

# Method 2:
rand_arr = np.random.uniform(5, 10, size=(5,3))
print(rand_arr)

[[6.69061424 8.95131061 6.93775394]
 [7.70776125 7.65587762 5.56475592]
 [5.15911486 8.7524139  9.1414033 ]
 [9.20987611 7.50087428 7.50792853]
 [7.28362595 7.95100909 5.69596753]]
[[8.49940521 8.32347975 7.47265203]
 [7.15297712 6.87709299 5.05603391]
 [6.14177678 7.08041602 9.08561937]
 [9.88221585 7.48382341 7.65111609]
 [9.83341968 9.29236629 7.16818903]]


21: Compute the mean, median, and standard deviation of a NumPy array

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 100, 200, 300])

mean = np.mean(arr)

median = np.median(arr)

std_div = np.std(arr)

print("Mean: ",mean)
print("Median: ",median)
print("Standard Deviation: ",std_div)

Mean:  110.0
Median:  65.0
Standard Deviation:  107.08252269472673


21. Print Only 3 Decimal Places

In [5]:
rand_arr = np.random.random([5,3])

np.set_printoptions(precision=3)
print(rand_arr[:4])


[[0.933 0.305 0.822]
 [0.101 0.89  0.005]
 [0.112 0.339 0.782]
 [0.712 0.739 0.108]]


22. Suppress Scientific Notation in Print Output

In [ ]:
import numpy as np
np.random.seed(10)
rand_arr = np.random.random([3,3])/1e3

np.set_printoptions(suppress= True,precision=6)
print(rand_arr)

[[0.007713 0.000208 0.006336]
 [0.007488 0.004985 0.002248]
 [0.001981 0.007605 0.001691]]


23. Limit the Number of Printed Items

In [ ]:
import numpy as np
np.set_printoptions(threshold=4)
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


24. Print the Full Array Without Truncating

In [32]:
import numpy as np
import sys
np.set_printoptions(threshold=4)
a = np.arange(15)
print(a)

np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


25. Import a Dataset With Mixed Types

In [ ]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


26. Extract a Particular Column From a 1D Structured Array

In [8]:
# Extract the text column species (5th field) from the 1D structured array iris_1d.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

species = np.array([row[0] for row in iris_1d])
print(species[:5])


[5.1 4.9 4.7 4.6 5. ]


27. Convert a 1D Structured Array to a 2D Numeric Array
Convert the 1D structured array iris_1d to a 2D array iris_2d by omitting the species

In [11]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


28. Compute Mean, Median, and Standard Deviation
Find the mean, median, and standard deviation of the sepallength column (1st column

In [15]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
np.set_printoptions(precision=3)
print(round(mu, 2), round(med, 2), round(sd, 2))

5.84 5.8 0.83


29. Normalize an Array to the 0-1 Range
Normalize the sepallength array so the minimum maps to 0 and the maximum maps to 1

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax , Smin = sepallength.max(), sepallength.min()

s = (sepallength - Smin)/ (Smax-Smin)
np.set_printoptions(precision=2)

print(s)

[0.22 0.17 0.11 0.08 0.19 0.31 0.08 0.19 0.03 0.17 0.31 0.14 0.14 0.
 0.42 0.39 0.31 0.22 0.39 0.22 0.31 0.22 0.08 0.22 0.14 0.19 0.19 0.25
 0.25 0.11 0.14 0.31 0.25 0.33 0.17 0.19 0.33 0.17 0.03 0.22 0.19 0.06
 0.03 0.19 0.22 0.14 0.22 0.08 0.28 0.19 0.75 0.58 0.72 0.33 0.61 0.39
 0.56 0.17 0.64 0.25 0.19 0.44 0.47 0.5  0.36 0.67 0.36 0.42 0.53 0.36
 0.44 0.5  0.56 0.5  0.58 0.64 0.69 0.67 0.47 0.39 0.33 0.33 0.42 0.47
 0.31 0.47 0.67 0.56 0.36 0.33 0.33 0.5  0.42 0.19 0.36 0.39 0.39 0.53
 0.22 0.39 0.56 0.42 0.78 0.56 0.61 0.92 0.17 0.83 0.67 0.81 0.61 0.58
 0.69 0.39 0.42 0.58 0.61 0.94 0.94 0.47 0.72 0.36 0.94 0.56 0.67 0.81
 0.53 0.5  0.58 0.81 0.86 1.   0.58 0.56 0.5  0.94 0.56 0.58 0.47 0.72
 0.67 0.72 0.42 0.69 0.67 0.67 0.56 0.61 0.53 0.44]


30. Compute the Softmax Score
Compute the softmax scores for the sepallength array.

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    "compute softmax values for each sets of scores in x"
    e_x =  np.exp(x-np.max(x))
    return e_x/ e_x.sum(axis=0)

print(softmax(sepallength))

[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.01 0.01 0.01 0.   0.01 0.
 0.01 0.   0.01 0.   0.   0.   0.01 0.01 0.   0.01 0.   0.   0.01 0.
 0.   0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.   0.   0.   0.   0.01
 0.   0.01 0.01 0.01 0.   0.   0.   0.01 0.   0.   0.   0.   0.   0.01
 0.   0.   0.01 0.   0.02 0.01 0.01 0.03 0.   0.02 0.01 0.02 0.01 0.01
 0.01 0.   0.   0.01 0.01 0.03 0.03 0.01 0.01 0.   0.03 0.01 0.01 0.02
 0.01 0.01 0.01 0.02 0.02 0.04 0.01 0.01 0.01 0.03 0.01 0.01 0.01 0.01
 0.01 0.01 0.   0.01 0.01 0.01 0.01 0.01 0.01 0.  ]


31. Find Percentile Scores
Find the 5th and 95th percentile of the sepallength array.

In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

result = np.percentile(sepallength, q=[5, 95])
print(result)

[4.6   7.255]


32. Insert Values at Random Positions
Insert np.nan at 20 random positions in the iris_2d dataset.


In [3]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


33. Find the Position of Missing Values
Find the number and position of missing values in iris_2d‘s sepallength (1st column).

In [4]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 4
Position of missing values: 
 (array([14, 34, 79, 87]),)
