##### 1. Create a 1D NumPy array of numbers from 0 to 9

In [1]:
import numpy as np

z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#####  2: Convert 1D array to 2D

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
arr_2d = arr.reshape(2, 3)
print(arr_2d)
print(arr_2d.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


##### Exercise 3: Print Array Attributes

In [9]:
arr = np.arange(10)
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print(my_array.shape)
print(my_array.ndim)
print(my_array.itemsize)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

(4, 2)
2
2
(10,)
1
8


Create a 3×3 NumPy array of all True

In [14]:
z = np.zeros((3,3),dtype=bool)
print(z)

[[False False False]
 [False False False]
 [False False False]]


5: Extract the documentation of NumPy’s

In [15]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

6: Create a 1D array filled with zeros and another filled with ones

In [20]:
zero_arr = np.zeros(10)
ones_arr = np.ones(10)

print("Zeros: ",zero_arr)
print("Ones ",ones_arr)

Zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


7: Create a 1D array of 10 evenly spaced values between 5 and 50

In [2]:
import numpy as np 
arr = np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


8: Convert a Python list into a NumPy array

In [4]:
py_list = [1, 2, 3, 4, 5, 6]

arr = np.array(py_list)
print(arr)

[1 2 3 4 5 6]


9: Find the memory size of a NumPy array of numbers from 0 to 9

In [8]:
arr = np.arange(10)

print("Array: ",arr)
print("Memory size in bytes: ",arr.nbytes)

Array:  [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes:  80


10: Reverse a 1D NumPy array

In [19]:
arr = np.arange(10)
reversed_array = arr[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


11: Create a 3×3 identity matrix

In [21]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12: Create a 4×4 array and extract its first row and last column
Expected Output:

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]

In [46]:
arr = np.arange(16).reshape(4,4)
print("Array:\n",arr)
print("First Row: ",arr[0, :])
print("Last Column: ",arr[0:,-1])

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
First Row:  [0 1 2 3]
Last Column:  [ 3  7 11 15]


13: Extract Odd Rows and Even Columns

In [3]:
import numpy as np
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])

new_array = sampleArray[1::2, ::2]

print("Original Array: \n",sampleArray)

print("New array with odd rows and even columns: \n",new_array)

Original Array: 
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
New array with odd rows and even columns: 
 [[15 21]
 [39 45]]


14: Stack arrays horizontally

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_arr = np.hstack((a,b))
print("Horizontally Stacked Array: \n",stacked_arr)

Horizontally Stacked Array: 
 [1 2 3 4 5 6]


 15: Slice the first two rows and first two columns from a 4×4 array

In [13]:
arr = np.arange(1, 17).reshape(4,4)
print("Original AArray: \n",arr)

sliced_arr = arr[:2, :2]
print(sliced_arr)

Original AArray: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2]
 [5 6]]


16: Replace all odd numbers in a NumPy array with -1

In [19]:
arr = np.arange(1, 11)
print("Original array: ",arr)

arr[arr % 2 == 1] = -1
print("modified_arr: ",arr)

Original array:  [ 1  2  3  4  5  6  7  8  9 10]
modified_arr:  [-1  2 -1  4 -1  6 -1  8 -1 10]


17: Get the indices of non-zero elements in an array


In [20]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print("Array: ",arr)

indices = np.nonzero(arr)
print("Indices of non zero elements: ",indices)


Array:  [1 0 2 0 3 0 4]
Indices of non zero elements:  (array([0, 2, 4, 6]),)


18: Find the common items between two arrays

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array([2, 4, 5, 6, 7])

common_elem = np.intersect1d(a,b)
print("Common items between two arrays:\n",common_elem)

Common items between two arrays:
 [2 4 5 6 7]


19: Perform arithmetic operations on two NumPy arrays element-wise

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum = np.add(a,b)
print("Element wise sum: ",sum)

prod = np.multiply(a,b)
print("Element wise multiplication: ",prod)

Element wise sum:  [5 7 9]
Element wise multiplication:  [ 4 10 18]


20: Matrix multiplication


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


matrix_multiply = np.matmul(a,b)
print("Dot product: ",matrix_multiply)

# or 

dot_prod = np.dot(a,b)
print("Dot product: ",dot_prod)

# or

dot_product = a @ b
print("Dot product: ",dot_product)


Dot product:  32
Dot product:  32
Dot product:  32


21: Compute the mean, median, and standard deviation of a NumPy array

variance = 

In [ ]:
arr = np.array([10, 20, 30, 100, 200, 300])

mean = np.mean(arr)
print("Mean: ",mean)

# or

mean = np.sum(arr)/len(arr)
print("Mean: ",mean)



median = np.median(arr)
print("Median: ",median)



variance = np.sum((arr-mean)**2)/ len(arr)
print("Variance: ",variance)

std_div = np.std(arr)
print("Standarad Deviation: ",std_div)

# or 

standard_deviation = np.sqrt(variance)
print(standard_deviation)


Mean:  110.0
Median:  65.0
Variance:  11466.666666666666
Standarad Deviation:  107.08252269472673
107.08252269472673


 22: Remove common items from array

In [36]:


import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Create a boolean mask where `a`'s elements are NOT in `b`
mask = np.isin(a, b)
print(mask)

# Use the `~` operator to invert the mask (get the opposite)
result = b[~mask]
print(result)

[False False False False  True]
[5 6 7 8]


23: Normalize a NumPy array (values between 0 and 1)

norm =   x - xmin  / xmax- xmin

In [38]:
arr = np.array([10, 20, 30, 40, 50])

normailzed = (arr - arr.min())/ (arr.max() - arr.min())

print("Normalized Array: ",normailzed)

Normalized Array:  [0.   0.25 0.5  0.75 1.  ]


 24: Get the positions where elements of array a and b match

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

position = np.where(a[::] == b[::])
print(position)
#  or 
index = np.where(a==b)
print(index)

(array([0, 2]),)
(array([0, 2]),)


25: Extract numbers from an array

Write a code to extract all numbers from an array that are between 5 and 10 (inclusive).

In [ ]:
arr = np.arange(15)

extracted = arr[(arr >= 5) & (arr <= 10)]
print(extracted)

[ 5  6  7  8  9 10]


26: Create a random 3×2 matrix and find its maximum and minimum values

In [14]:
import  numpy as np
matrix = np.random.random((3,2))
matrix = np.round(matrix, 2)
print(matrix)

print("Max Value: ",matrix.max())
print("Min Value: ",matrix.min())

[[0.83 0.52]
 [0.25 0.51]
 [0.49 0.27]]
Max Value:  0.83
Min Value:  0.25


 27: Sorting a NumPy array based on a specific column

In [18]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])


sorted_indices = sampleArray[:, 2].argsort()

sorted_array = sampleArray[sorted_indices]

print("Original array:\n",sampleArray)

print("Sorted Array:\n",sorted_array)

Original array:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorted Array:
 [[82 22 12]
 [53 94 66]
 [34 43 73]]


28: Delete and Insert a Column in a NumPy Array

In [20]:
sampleArray = np.array([[1, 2, 3], [15, 19, 21], [10, 20, 30]])
new_column = np.array([10, 10, 10])

deletedArray = np.delete(sampleArray, 1, axis=1)

resultedArray = np.insert(deletedArray, 1, new_column, axis= 1)

print(resultedArray)

[[ 1 10  3]
 [15 10 21]
 [10 10 30]]


30: Generate 10 random integers between 1 and 100


In [25]:
arr = np.random.randint(1, 100, (3,4))
print(arr)

[[11 57 31 71]
 [54 60 38 11]
 [10 25 26 19]]


29: Swap column 1 and 2 in a 2D array


In [ ]:
# column swap
arr = np.arange(9).reshape(3, 3)
print("Before:\n",arr)

arr[:, [1, 2]] = arr[:, [2, 1]]
print("After:\n",arr)

# row swap
print("Before:\n",arr)

arr[[1, 2], :] = arr[[2, 1], :]
print("After:\n",arr)

Before:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]
Before:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]
After:
 [[0 2 1]
 [6 8 7]
 [3 5 4]]


Own : generate the random integers 3x4 matrix and change the specific elements

In [1]:
import numpy as np
arr = np.random.randint(1, 100, (3,4))
arr[1,3] = 99
print(arr)

[[76 49 75 61]
 [27 91 45 99]
 [76  3 35 52]]


31: Create a 3×3 array of random integers and sort it row-wise

In [8]:
arr = np.random.randint(0,100, (3,3))
print("Original Array: \n",arr)

row_sort = np.sort(arr, axis =1)
print("Sorted array: \n",row_sort)

Original Array: 
 [[33  3 27]
 [61 36  3]
 [26 18 97]]
Sorted array: 
 [[ 3 27 33]
 [ 3 36 61]
 [18 26 97]]


 32: Shuffle an array randomly

In [ ]:
arr = np.arange(10)

print("Original Array: ",arr)

np.random.shuffle(arr)
print("Shuffeled array: ",arr)



Original Array:  [0 1 2 3 4 5 6 7 8 9]
Shuffeled array:  [3 2 6 1 8 0 7 9 5 4]


33: Create a 5×5 2D array with 1s on the border and 0s inside.

In [ ]:
arr_2d = np.ones((5,5))

arr_2d[1:-1, 1:-1] = 0
# print(arr_2d)

print(arr_2d)
arr_2d[0, :] = 0
arr_2d[4, :] = 0
arr_2d[:, 0] = 0
arr_2d[:, 4] = 0
print(arr_2d)
# or

arr = np.ones((5,5))
arr[[0, -1], :] = 0
arr[:, [0, -1]] = 0
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


 34: Check if an array contains any NaN values.

In [50]:
import numpy as np
a = np.array([1, 2, np.nan, 4, 5])

b = np.isnan(a).any()
print(b)

True


35: Sort the rows of a 2D array based on the values of the second column

In [52]:
arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])

sorted_indices = arr[:, 2].argsort()

sorted_array = arr[sorted_indices]
print(sorted_array)

[[8 4 1]
 [6 9 3]
 [5 2 7]]


36: Flatten a multi-dimensional NumPy array

In [58]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Original Array:\n",arr)

flattned_arr = arr.flatten()
print("flattened array: ",flattned_arr)

Original Array:
 [[1 2]
 [3 4]
 [5 6]]
flattened array:  [1 2 3 4 5 6]


37: Stack two arrays vertically and horizontally

In [61]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical = np.vstack((a,b))
horizontal = np.hstack((a,b))

print("Vertical Stack:\n",vertical)
print("horizontal Stack:\n ",horizontal)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
horizontal Stack:
  [1 2 3 4 5 6]


 38: Split an array into 3 equal parts

In [71]:
arr = np.arange(9)

print("Original Array: ",arr)
print("Split Arrays: ",np.split(arr,3))

Original Array:  [0 1 2 3 4 5 6 7 8]
Split Arrays:  [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


39: Perform Addition and Squaring on Arrays

In [ ]:
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

add_arr = np.add(arrayOne, arrayTwo)
print("Result of array Addition:\n", add_arr)

# or

result_arr = arrayOne + arrayTwo
print("Result of array Addition:\n", result_arr)

suqred_arr = add_arr**2
print("Result with each element squared:\n",suqred_arr)
# or
suqred_arr = result_arr**2
print("Result with each element squared:\n",suqred_arr)

Result of array Addition:
 [[20 39 33]
 [25 25 28]]
Result of array Addition:
 [[20 39 33]
 [25 25 28]]
Result with each element squared:
 [[ 400 1521 1089]
 [ 625  625  784]]
Result with each element squared:
 [[ 400 1521 1089]
 [ 625  625  784]]


40: Invert a matrix

In [82]:
arr = np.array([[1, 2], [3, 4]])
inv_arr = np.linalg.inv(arr)
print(inv_arr)

[[-2.   1. ]
 [ 1.5 -0.5]]


41: Use boolean indexing to filter values less than a given number

In [ ]:
import numpy as np
arr = np.array([5, 12, 29, 30, 44, 7, 18])

mask = arr < 30
print("Values <30: ",mask)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2344219919.py, line 5)

42: Count the number of occurrences of each unique element

In [5]:
arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])

vals, counts = np.unique(arr, return_counts= True)
for v, c in zip(vals, counts):
    print(f"Value {v} occurs {3} time(s)")

Value 2 occurs 3 time(s)
Value 3 occurs 3 time(s)
Value 5 occurs 3 time(s)


43: Find the intersection and union of two arrays

In [7]:
a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

print("Intersection: ",np.intersect1d(a,b))
print("Union: ",np.union1d(a,b))

Intersection:  [3 5 7]
Union:  [1 2 3 4 5 6 7]


44: Transpose a matrix

In [12]:
arr = np.array([[1, 2], [3, 4]])

# transposed = np.transpose(arr)
# or 
transposed = arr.T

print("Transposed Matrix:\n",transposed)

Transposed Matrix:
 [[1 3]
 [2 4]]


45: Compute the eigenvalues and eigenvectors of a matrix

In [15]:
A = np.array([[4, 2],
              [1, 3]])

eigvals , eigvecs = np.linalg.eig(A)

print("Eigen Values: \n",eigvals)
print("Eigen Vectors: \n",eigvecs)



Eigen Values: 
 [5. 2.]
Eigen Vectors: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


46: Solve a linear equation
Solve the system of linear equations: x + 2y = 8 and 3x + 4y = 18.

In [18]:
a = np.array([[1, 2], [3, 4]])

b = np.array([8, 18])

solution = np.linalg.solve(a,b)
print(solution)

[2. 3.]


In [26]:

import numpy as np

arr = np.ones((8,8), dtype=int)

arr[::2, ::2] = 0
arr[1::2, 1::2] = 0


print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 48: Find nearest value
Find the value in an array that is closest to a number 3.

In [32]:
arr = np.array([1.5, 2.8, 3.2, 4.1])
targetValue = 3

index = np.abs(arr - targetValue).argmin()


nearst_value = arr[index]
print(nearst_value)

2.8


Exercise 49: Convert to object array
Convert a 1D array to an object array, retaining the original data type of each element.

In [35]:
arr = np.array([1, 2, 3, 4, 5])

obj_arr = np.empty(arr.size, dtype='object')

obj_arr[:] = arr

obj_arr[1] = 'a'

print(obj_arr)
print(obj_arr.dtype)

[1 'a' 3 4 5]
object


50: Compute the mean, median, and standard deviation of a NumPy array

In [ ]:
arr = np.array([10, 20, 30, 100, 200, 300])

mean = np.mean(arr)
median = np.median(arr)
std_div = np.std(arr)

print("Mean: ",mean)
print("Median: ",median)
print("Standard Deviation: ",std_div)

Mean:  110.0
Median:  65.0
Standard Deviation 107.08252269472673
