##### 1. Create a 1D NumPy array of numbers from 0 to 9

In [1]:
import numpy as np

z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#####  2: Convert 1D array to 2D

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
arr_2d = arr.reshape(2, 3)
print(arr_2d)
print(arr_2d.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


##### Exercise 3: Print Array Attributes

In [9]:
arr = np.arange(10)
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print(my_array.shape)
print(my_array.ndim)
print(my_array.itemsize)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

(4, 2)
2
2
(10,)
1
8


Create a 3×3 NumPy array of all True

In [14]:
z = np.zeros((3,3),dtype=bool)
print(z)

[[False False False]
 [False False False]
 [False False False]]


5: Extract the documentation of NumPy’s

In [15]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

6: Create a 1D array filled with zeros and another filled with ones

In [20]:
zero_arr = np.zeros(10)
ones_arr = np.ones(10)

print("Zeros: ",zero_arr)
print("Ones ",ones_arr)

Zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


7: Create a 1D array of 10 evenly spaced values between 5 and 50

In [2]:
import numpy as np 
arr = np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


8: Convert a Python list into a NumPy array

In [4]:
py_list = [1, 2, 3, 4, 5, 6]

arr = np.array(py_list)
print(arr)

[1 2 3 4 5 6]


9: Find the memory size of a NumPy array of numbers from 0 to 9

In [8]:
arr = np.arange(10)

print("Array: ",arr)
print("Memory size in bytes: ",arr.nbytes)

Array:  [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes:  80


10: Reverse a 1D NumPy array

In [19]:
arr = np.arange(10)
reversed_array = arr[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


11: Create a 3×3 identity matrix

In [21]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12: Create a 4×4 array and extract its first row and last column
Expected Output:

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]

In [46]:
arr = np.arange(16).reshape(4,4)
print("Array:\n",arr)
print("First Row: ",arr[0, :])
print("Last Column: ",arr[0:,-1])

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
First Row:  [0 1 2 3]
Last Column:  [ 3  7 11 15]


13: Extract Odd Rows and Even Columns

In [3]:
import numpy as np
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])

new_array = sampleArray[1::2, ::2]

print("Original Array: \n",sampleArray)

print("New array with odd rows and even columns: \n",new_array)

Original Array: 
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
New array with odd rows and even columns: 
 [[15 21]
 [39 45]]


14: Stack arrays horizontally

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_arr = np.hstack((a,b))
print("Horizontally Stacked Array: \n",stacked_arr)

Horizontally Stacked Array: 
 [1 2 3 4 5 6]


 15: Slice the first two rows and first two columns from a 4×4 array

In [13]:
arr = np.arange(1, 17).reshape(4,4)
print("Original AArray: \n",arr)

sliced_arr = arr[:2, :2]
print(sliced_arr)

Original AArray: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2]
 [5 6]]


16: Replace all odd numbers in a NumPy array with -1

In [19]:
arr = np.arange(1, 11)
print("Original array: ",arr)

arr[arr % 2 == 1] = -1
print("modified_arr: ",arr)

Original array:  [ 1  2  3  4  5  6  7  8  9 10]
modified_arr:  [-1  2 -1  4 -1  6 -1  8 -1 10]


17: Get the indices of non-zero elements in an array


In [20]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print("Array: ",arr)

indices = np.nonzero(arr)
print("Indices of non zero elements: ",indices)


Array:  [1 0 2 0 3 0 4]
Indices of non zero elements:  (array([0, 2, 4, 6]),)
