##### 1. Create a 1D NumPy array of numbers from 0 to 9

In [1]:
import numpy as np

z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#####  2: Convert 1D array to 2D

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
arr_2d = arr.reshape(2, 3)
print(arr_2d)
print(arr_2d.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


##### Exercise 3: Print Array Attributes

In [9]:
arr = np.arange(10)
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print(my_array.shape)
print(my_array.ndim)
print(my_array.itemsize)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

(4, 2)
2
2
(10,)
1
8


Create a 3×3 NumPy array of all True

In [14]:
z = np.zeros((3,3),dtype=bool)
print(z)

[[False False False]
 [False False False]
 [False False False]]


5: Extract the documentation of NumPy’s

In [15]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

6: Create a 1D array filled with zeros and another filled with ones

In [20]:
zero_arr = np.zeros(10)
ones_arr = np.ones(10)

print("Zeros: ",zero_arr)
print("Ones ",ones_arr)

Zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
