##### 1. Create a 1D NumPy array of numbers from 0 to 9

In [2]:
import numpy as np

z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#####  2: Convert 1D array to 2D

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
arr_2d = arr.reshape(2, 3)
print(arr_2d)
print(arr_2d.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


##### Exercise 3: Print Array Attributes

In [9]:
arr = np.arange(10)
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print(my_array.shape)
print(my_array.ndim)
print(my_array.itemsize)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

(4, 2)
2
2
(10,)
1
8
