##### 1. import numpy module as np

In [2]:
import numpy as np

##### 2. Print the numpy version and the configuration

In [5]:
print(np.__version__)
np.show_config()

2.4.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35222",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35222",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.dev",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-awnw0lvp/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "l

c:\Users\chand\OneDrive\Desktop\NUMPY\venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


 ##### 3. Create a null vector of size 10

In [6]:
z = np.zeros(10)
print("Null vector:\n",z)

Null vector:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### 4. How to find the memory size of any array 

In [9]:
z = np.ones((10,10))
print("%d bytes" %(z.size*z.itemsize))

# Simpler alternative
print("%d bytes" %(z.nbytes))


800 bytes
800 bytes


##### 6. Create a null vector of size 10 but the fifth value which is 1

In [11]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


##### 7. Create a vector with values ranging from 10 to 49

In [14]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


##### 8. Reverse a vector (first element becomes last)

In [ ]:
Z = np.arange(50)
# Z[start : stop : step]
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


##### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


##### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

#  OR

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)
(array([0, 1, 4]),)


##### 11. Create a 3x3 identity matrix

In [22]:
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 12. Create a 3x3x3 array with random values

In [32]:
import random as random
arr = np.random.random((3,3,3))
print(arr)

[[[6.23883433e-01 7.36413329e-01 3.06359838e-01]
  [5.59416195e-02 2.49122487e-01 6.10755419e-04]
  [7.88190262e-01 5.79052698e-02 8.50298974e-02]]

 [[2.31476016e-01 6.61479397e-02 5.42252944e-01]
  [6.83249450e-01 2.88876930e-01 7.77703411e-01]
  [7.10187983e-01 1.79944856e-01 1.87718959e-03]]

 [[7.51058584e-01 4.30046620e-01 6.12210990e-01]
  [9.91743590e-01 6.91638639e-01 6.28225107e-01]
  [2.93389742e-02 9.65502562e-01 7.74568243e-01]]]


##### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [35]:
arr = np.random.random((10,10))
print("Array:\n",arr)
print(arr.max())
print(arr.min())

# OR

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

Array:
 [[0.01907468 0.12544992 0.87951556 0.52262052 0.02924185 0.83398319
  0.09678958 0.37361462 0.40546313 0.57058913]
 [0.63862548 0.74014429 0.58921782 0.01423149 0.63278793 0.68073931
  0.46298047 0.37087087 0.65912835 0.88191711]
 [0.3670991  0.58406736 0.19608136 0.27749307 0.5518401  0.61248802
  0.30426559 0.38902514 0.49492231 0.30266714]
 [0.07535147 0.5095199  0.81518294 0.44802427 0.13995007 0.85823044
  0.89491898 0.31270346 0.90306599 0.18955692]
 [0.83444837 0.79878636 0.99788092 0.37412893 0.07915176 0.65134623
  0.35431659 0.47461756 0.9781968  0.0686819 ]
 [0.69625819 0.02555123 0.87607113 0.60745162 0.74874106 0.74160936
  0.18600008 0.75863385 0.78688179 0.61907902]
 [0.12608199 0.99278709 0.28777811 0.52096088 0.81552708 0.63768776
  0.36674131 0.79865757 0.54410038 0.77853971]
 [0.81281171 0.21398116 0.56662875 0.86497659 0.1366655  0.19447535
  0.08150573 0.46640155 0.77743531 0.62644682]
 [0.97815473 0.82391016 0.4491569  0.20200196 0.81980738 0.62854655
  0.

##### 14. Create a random vector of size 30 and find the mean value

In [43]:
Z = np.random.random(30)
mean = Z.mean()
print("random Vector:\n",Z)
print("Mean Value: ",mean)


random Vector:
 [0.07212958 0.50905903 0.7445876  0.42606239 0.86602613 0.80265953
 0.21192401 0.08455884 0.75295926 0.31267544 0.92125861 0.24582685
 0.23467119 0.70129777 0.56233382 0.56668894 0.70129987 0.09259372
 0.6431069  0.68459457 0.80097166 0.24072002 0.28493663 0.7424698
 0.10171067 0.88825277 0.76688509 0.21221656 0.05163025 0.71797534]
Mean Value:  0.4981360946432297


##### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1,mode="constant", constant_values=0)
print(Z) 


# OR

Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


##### 17. What is the result of the following expression?

In [3]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)



nan
False
False
nan
True
False


##### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


##### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [14]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


##### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [15]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


##### 21. Create a checkerboard 8x8 matrix using the tile function

In [16]:
Z = np.tile([[1,0], [0,1]],(4,4))
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


##### 22. Normalize a 5x5 random matrix

In [19]:
x = np.random.rand(5,5)

x_mean = np.mean(x)
x_std_dev = np.std(x)

normalized_x = (x- x_mean)/x_std_dev

print(normalized_x)

# or

Z = (x - np.mean(x))/(np.std(x))
print("\n",Z)

[[-1.51540829  0.90837686  0.67961578  0.07099391  0.87012641]
 [ 0.68193484 -1.63702004 -0.95796487  1.33421503 -1.62882161]
 [ 1.52133026 -0.65710838  0.52328107  0.42854194  0.66992132]
 [ 0.09028436  0.96714222  1.09460616  0.3831974   0.185844  ]
 [-0.94291341 -1.42175437 -0.92884961 -1.39682748  0.6772565 ]]

 [[-1.51540829  0.90837686  0.67961578  0.07099391  0.87012641]
 [ 0.68193484 -1.63702004 -0.95796487  1.33421503 -1.62882161]
 [ 1.52133026 -0.65710838  0.52328107  0.42854194  0.66992132]
 [ 0.09028436  0.96714222  1.09460616  0.3831974   0.185844  ]
 [-0.94291341 -1.42175437 -0.92884961 -1.39682748  0.6772565 ]]


##### 23. Create a custom dtype that describes a color as four unsigned bytes

In [22]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


##### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)



In [27]:
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# or 

z = np.ones((5,3)) @ np.ones((3,2))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


##### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [31]:
c = np.arange(11)
c[(3<c) & (8<c)] *= -1
print(c)


[  0   1   2   3   4   5   6   7   8  -9 -10]


##### 26. What is the output of the following script?

In [42]:
print(sum(range(5),0))
from numpy import *
print(sum(range(5),-1))

10
10
